enum FontType {
  OPENSANS_REGULAR = 'OPENSANS_REGULAR',
  OPENSANS_MEDIUM = 'OPENSANS_MEDIUM',
  OPENSANS_BOLD = 'OPENSANS_BOLD',
  OPENSANS_SEMIBOLD = 'OPENSANS_SEMIBOLD',
}

enum ButtonType {
  PRIMARY = 'PRIMARY',
  OUTLINE = 'OUTLINE',
  DISABLE = 'DISABLE',
}

export {FontType, ButtonType};
